name: Atualização Diária

on:
  schedule:
    - cron: '30 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build Docker Image
      run: docker build -t erikamayarapimentel/mapa-escolas-docker:latest .

    - name: Login no Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push para Docker Hub
      run: docker push erikamayarapimentel/mapa-escolas-docker:latest

    - name: Commit e push das alterações
      run: |
        git config --global user.email "tiaerikadev@gmail.com"
        git config --global user.name "Erika Mayara Pimentel"
        git add .
        git commit -m "Atualização diária"
        git push
